# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewitis.ui'
#
# Created: Wed Sep 29 20:46:46 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 491)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_runs = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_runs.setGeometry(QtCore.QRect(10, 10, 321, 381))
        self.tableWidget_runs.setAutoFillBackground(False)
        self.tableWidget_runs.setDragEnabled(False)
        self.tableWidget_runs.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget_runs.setAlternatingRowColors(True)
        self.tableWidget_runs.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_runs.setObjectName("tableWidget_runs")
        self.tableWidget_runs.setColumnCount(3)
        self.tableWidget_runs.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_runs.setItem(2, 2, item)
        self.tableWidget_runs.verticalHeader().setVisible(True)
        self.tableWidget_runs.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_times = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget_times.setGeometry(QtCore.QRect(350, 10, 451, 381))
        self.tableWidget_times.setAutoFillBackground(False)
        self.tableWidget_times.setDragEnabled(False)
        self.tableWidget_times.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.tableWidget_times.setAlternatingRowColors(True)
        self.tableWidget_times.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_times.setObjectName("tableWidget_times")
        self.tableWidget_times.setColumnCount(4)
        self.tableWidget_times.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_times.setItem(2, 3, item)
        self.tableWidget_times.verticalHeader().setVisible(True)
        self.tableWidget_times.verticalHeader().setDefaultSectionSize(20)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 20))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_Port = QtGui.QToolBar(MainWindow)
        self.toolBar_Port.setEnabled(True)
        self.toolBar_Port.setObjectName("toolBar_Port")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Port)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.aSetPort = QtGui.QAction(MainWindow)
        self.aSetPort.setEnabled(True)
        self.aSetPort.setObjectName("aSetPort")
        self.aConnectPort = QtGui.QAction(MainWindow)
        self.aConnectPort.setObjectName("aConnectPort")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelo = QtGui.QAction(MainWindow)
        self.actionHelo.setObjectName("actionHelo")
        self.menuAbout.addAction(self.actionHelo)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar_Port.addAction(self.aSetPort)
        self.toolBar_Port.addSeparator()
        self.toolBar_Port.addAction(self.aConnectPort)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.setSortingEnabled(True)
        self.tableWidget_runs.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Sloupec1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "sloupec 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Sloupec3", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_runs.isSortingEnabled()
        self.tableWidget_runs.setSortingEnabled(False)
        self.tableWidget_runs.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(0, 2).setText(QtGui.QApplication.translate("MainWindow", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "aa", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "bb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(1, 2).setText(QtGui.QApplication.translate("MainWindow", "cc", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "aa", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "bbb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.item(2, 2).setText(QtGui.QApplication.translate("MainWindow", "cccc", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_runs.setSortingEnabled(__sortingEnabled)
        self.tableWidget_times.setSortingEnabled(True)
        self.tableWidget_times.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Sloupec1", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "sloupec 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Sloupec3", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Sloupec 4", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget_times.isSortingEnabled()
        self.tableWidget_times.setSortingEnabled(False)
        self.tableWidget_times.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(0, 1).setText(QtGui.QApplication.translate("MainWindow", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(0, 2).setText(QtGui.QApplication.translate("MainWindow", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(0, 3).setText(QtGui.QApplication.translate("MainWindow", "d", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "aa", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(1, 1).setText(QtGui.QApplication.translate("MainWindow", "bb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(1, 2).setText(QtGui.QApplication.translate("MainWindow", "cc", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(1, 3).setText(QtGui.QApplication.translate("MainWindow", "dd", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "aa", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(2, 1).setText(QtGui.QApplication.translate("MainWindow", "bbb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(2, 2).setText(QtGui.QApplication.translate("MainWindow", "cccc", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.item(2, 3).setText(QtGui.QApplication.translate("MainWindow", "dddd", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_times.setSortingEnabled(__sortingEnabled)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Menu1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Port.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.aSetPort.setText(QtGui.QApplication.translate("MainWindow", "PORT", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setToolTip(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelo.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ewitis.ui'
#
# Created: Tue Nov 09 12:34:25 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 491)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 350, 31, 31))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../_meloun/myPython/ewitis/src/ewitis/gui/img/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.RunsProxyView = QtGui.QTreeView(self.centralwidget)
        self.RunsProxyView.setGeometry(QtCore.QRect(10, 30, 431, 321))
        self.RunsProxyView.setObjectName("RunsProxyView")
        self.RunsFilterLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.RunsFilterLineEdit.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.RunsFilterLineEdit.setObjectName("RunsFilterLineEdit")
        self.TimesProxyView = QtGui.QTreeView(self.centralwidget)
        self.TimesProxyView.setGeometry(QtCore.QRect(450, 30, 431, 321))
        self.TimesProxyView.setObjectName("TimesProxyView")
        self.TimesFilterLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.TimesFilterLineEdit.setGeometry(QtCore.QRect(450, 10, 113, 20))
        self.TimesFilterLineEdit.setObjectName("TimesFilterLineEdit")
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 350, 31, 31))
        self.pushButton_6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../_meloun/myPython/ewitis/src/ewitis/gui/img/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 350, 31, 31))
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 350, 31, 31))
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 20))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_Port = QtGui.QToolBar(MainWindow)
        self.toolBar_Port.setEnabled(True)
        self.toolBar_Port.setObjectName("toolBar_Port")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar_Port)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.aSetPort = QtGui.QAction(MainWindow)
        self.aSetPort.setEnabled(True)
        self.aSetPort.setObjectName("aSetPort")
        self.aConnectPort = QtGui.QAction(MainWindow)
        self.aConnectPort.setObjectName("aConnectPort")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelo = QtGui.QAction(MainWindow)
        self.actionHelo.setObjectName("actionHelo")
        self.menuAbout.addAction(self.actionHelo)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar_Port.addAction(self.aSetPort)
        self.toolBar_Port.addSeparator()
        self.toolBar_Port.addAction(self.aConnectPort)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setToolTip(QtGui.QApplication.translate("MainWindow", "Smazat vybraný záznam", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Vložit záznam", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Vložit záznam", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Menu1", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_Port.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.aSetPort.setText(QtGui.QApplication.translate("MainWindow", "PORT", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.aConnectPort.setToolTip(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelo.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

